# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  # push:
  #   branches: [feature/live-preview]
  # pull_request:
  #   branches: [feature/live-preview]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Set Actions Allow Unsecure Commands
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Installing my packages
        run: npm install

      - name: Build Flivo Bot
        run: npm run build
        # env
        #   NEXT_PUBLIC_BASE_PATH: /chakra-nextjs-pro
      # - run: npm export
        # env:
      #     NEXT_PUBLIC_BASE_PATH: /chakra-nextjs-pro
      # - run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
